### ISSUE TITLE
Enum deserialization regression in version 2.8.0.rc1

### ISSUE THREAD

**Issue by Stephan202** [FasterXML/jackson-module-parameter-names#35]
Consider the following test extension:
```diff
diff --git a/src/test/java/com/fasterxml/jackson/module/paramnames/EnumNamingTest.java b/src/test/java/com/fasterxml/jackson/module/paramnames/EnumNamingTest.java
index a627af9..5daf72d 100644
--- a/src/test/java/com/fasterxml/jackson/module/paramnames/EnumNamingTest.java
+++ b/src/test/java/com/fasterxml/jackson/module/paramnames/EnumNamingTest.java
@@ -31,5 +31,10 @@ public class EnumNamingTest
             .registerModule(new ParameterNamesModule())
             .writeValueAsString(SurprisingEnum32.ENUM_NAME);
         assertEquals(EXP, json);
+
+        SurprisingEnum32 value = new ObjectMapper()
+            .registerModule(new ParameterNamesModule())
+            .readValue(json, SurprisingEnum32.class);
+        assertEquals(SurprisingEnum32.ENUM_NAME, value);
     }
 }
```

This causes the following failure:
```
testCustomEnumName(com.fasterxml.jackson.module.paramnames.EnumNamingTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.resolveType(BasicDeserializerFactory.java:1876)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.constructCreatorProperty(BasicDeserializerFactory.java:846)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._checkImplicitlyNamedConstructors(BasicDeserializerFactory.java:560)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:527)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:323)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createEnumDeserializer(BasicDeserializerFactory.java:1246)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:371)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:475)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3890)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3785)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
	at com.fasterxml.jackson.module.paramnames.EnumNamingTest.testCustomEnumName(EnumNamingTest.java:37)
```

Various failures in our private project indicate that when the `ParameterNamesModule` is enabled enum deserialization doesn't work anymore in version 2.8.0.rc1 and 2.8.0.rc2. The issue does not exist in version 2.7.5.

**Comment by cowtowncoder** [comment]
Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Unfortunately I can not reproduce the problem: modified test passes for me. Are you registering other modules? Which JVM are you running tests on?

**Comment by cowtowncoder** [comment]
Oddly enough, our CI system (travis) does show a failure, with Java 8 (I tried Java 7 and 8 locally, neither failed for me).

**Comment by cowtowncoder** [comment]
Ok. Now I can reproduce the problem locally as well. Not sure why test passed earlier; now it fails as reported.

**Comment by cowtowncoder** [comment]
Uh. Great. Looks like this might be a JDK bug... related to discrepancy between number of parameters an Enum constructor has and number of types FOR parameters that are returned; bug most likely due to hidden `this` parameter. I remember having had to add a work-around in another place, not sure what changed here to trigger the problem.

Will try to work around this somehow.

**Comment by Stephan202** [comment]
@cowtowncoder, I just tested the fix with our private code and it works, thanks!

NB: While originally debugging this issue in our code I got side-tracked by another "issue", for which I filed FasterXML/jackson-databind#1272.

**Comment by Stephan202** [comment]
@cowtowncoder, with the fix released this one can now be closed, correct? :)

Thanks again!

**Comment by cowtowncoder** [comment]
@Stephan202 correct thank you for reminder.
